events {
    worker_connections 1024;
}

http {
    upstream api_nodes {
        # O Nginx vai distribuir a carga entre os containers gerados pelo Docker Compose
        ip_hash;
        server notifications-api:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # Configurações obrigatórias para WebSockets e SSE funcionarem no Nginx
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            # Remove limite de tempo para o SSE/WS não cair por inatividade
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}